import { ArrowRight, BarChart3, CheckCircle2, Menu, ShieldCheck, Sparkles, X, Zap } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { LeadForm } from '../components/LeadForm.jsx';

const features = [{ icon: Sparkles, title: 'Capture every signal', copy: 'A polished enquiry flow that makes a strong first impression.' }, { icon: BarChart3, title: 'See the full picture', copy: 'Turn incoming interest into a clear, actionable pipeline.' }, { icon: ShieldCheck, title: 'Keep data protected', copy: 'Secure admin access, validated inputs, and thoughtful safeguards.' }];
const testimonials = [{ quote: 'LeadDesk gives our small team the calm and clarity of a much larger sales operation.', name: 'Maya Patel', role: 'Founder, Northstar Studio' }, { quote: 'We finally have a simple way to make sure warm enquiries never fall through the cracks.', name: 'Elliot James', role: 'Growth lead, Orbit Labs' }];
export function LandingPage() {
  const [open, setOpen] = useState(false); const links = ['Features', 'Why us', 'Stories', 'Contact'];
  return <div className="landing"><header className="site-header"><Link className="brand" to="/"><span>✦</span> LeadDesk</Link><nav className={open ? 'nav open' : 'nav'}>{links.map((label) => <a key={label} onClick={() => setOpen(false)} href={`#${label === 'Why us' ? 'why-us' : label.toLowerCase()}`}>{label}</a>)}<Link className="nav-login" to="/admin/login">Admin login</Link></nav><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X /> : <Menu />}</button></header>
    <main><section className="hero"><div className="hero-copy"><p className="eyebrow">A better front door for your business</p><h1>Turn interest into <em>momentum.</em></h1><p className="hero-text">LeadDesk keeps your best opportunities visible, organized, and moving — without giving your team another complicated system to learn.</p><a className="button primary" href="#contact">Start a conversation <ArrowRight size={18} /></a><div className="hero-proof"><div className="avatars"><i>J</i><i>M</i><i>S</i></div><span>Trusted by focused teams building what’s next</span></div></div><div className="hero-card"><div className="mini-label"><span className="live-dot" /> LIVE PIPELINE</div><div className="lead-preview"><div className="initial">AK</div><div><strong>Aisha Khan</strong><p>Interested in a website redesign</p></div><span className="status status-new">New</span></div><div className="lead-preview"><div className="initial rose">LR</div><div><strong>Leo Ramirez</strong><p>Product strategy consultation</p></div><span className="status status-contacted">Contacted</span></div><div className="chart"><div className="chart-caption"><span>Weekly activity</span><strong>+28%</strong></div><div className="bars">{[38, 55, 40, 72, 60, 89, 76].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div></div></div></section>
    <section id="features" className="section"><p className="eyebrow">Built for the work that matters</p><h2>Everything you need. Nothing you don’t.</h2><div className="feature-grid">{features.map(({ icon: Icon, title, copy }) => <article className="feature-card" key={title}><Icon /><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section id="why-us" className="section split-section"><div><p className="eyebrow">Why LeadDesk</p><h2>A system that stays out of your way.</h2><p className="section-copy">Your sales process should feel like a conversation, not administration. We make it easy to respond quickly, understand what matters, and follow through with confidence.</p><ul className="check-list">{['One clear home for every incoming lead', 'Simple status changes for fast team alignment', 'Useful reporting without spreadsheets'].map((item) => <li key={item}><CheckCircle2 />{item}</li>)}</ul></div><div className="stat-panel"><span>LEADS MANAGED</span><strong>12,480<span>+</span></strong><p>and every one has a clear next step</p><div><b>94%</b><span>of teams respond faster in their first month</span></div></div></section>
    <section id="stories" className="section testimonials"><p className="eyebrow">Loved by teams with taste</p><h2>Less busywork, better follow-through.</h2><div className="quote-grid">{testimonials.map((testimonial) => <blockquote key={testimonial.name}>“{testimonial.quote}”<footer><div className="quote-avatar">{testimonial.name[0]}</div><span><strong>{testimonial.name}</strong>{testimonial.role}</span></footer></blockquote>)}</div></section>
    <section id="contact" className="contact-section"><div><p className="eyebrow">Let’s make a good first impression</p><h2>Tell us what you’re working on.</h2><p>Share a little context and we’ll get back to you within one business day.</p><div className="contact-mark"><Zap /> Thoughtful work starts with a real conversation.</div></div><LeadForm /></section></main>
    <footer className="site-footer"><Link className="brand" to="/"><span>✦</span> LeadDesk</Link><p>© {new Date().getFullYear()} LeadDesk Mini</p><a href="https://digitalheroesco.com" target="_blank" rel="noreferrer">Built for Digital Heroes Training Task</a></footer></div>;
}
