import { Copy, Download, Search, Trash2 } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import api, { getError } from '../services/api.js';
import { Spinner } from '../components/Spinner.jsx';
import { StatusBadge } from '../components/StatusBadge.jsx';
const statuses = ['New', 'Contacted', 'Closed'];
export function LeadsPage() {
  const [result, setResult] = useState(); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [error, setError] = useState('');
  const load = useCallback(async () => { setError(''); setResult(undefined); try { const { data } = await api.get('/leads', { params: { page, search, limit: 10 } }); setResult(data); } catch (e) { setError(getError(e)); } }, [page, search]);
  useEffect(() => { const timeout = setTimeout(load, 250); return () => clearTimeout(timeout); }, [load]);
  async function changeStatus(lead, status) { if (status === lead.status) return; if (!window.confirm(`Change ${lead.name}'s status to ${status}?`)) return; try { await api.patch(`/leads/${lead._id}`, { status }); toast.success('Lead status updated.'); load(); } catch (e) { toast.error(getError(e)); } }
  async function deleteLead(lead) { if (!window.confirm(`Delete ${lead.name}'s lead permanently?`)) return; try { await api.delete(`/leads/${lead._id}`); toast.success('Lead removed.'); load(); } catch (e) { toast.error(getError(e)); } }
  function copyEmail(email) { navigator.clipboard.writeText(email).then(() => toast.success('Email copied.')).catch(() => toast.error('Could not copy email.')); }
  function exportCsv() { if (!result?.leads.length) return; const content = [['Name', 'Email', 'Budget', 'Message', 'Status', 'Created'], ...result.leads.map((lead) => [lead.name, lead.email, lead.budget, lead.message, lead.status, new Date(lead.createdAt).toISOString()])].map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([content], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = 'leaddesk-leads.csv'; link.click(); URL.revokeObjectURL(url); }
  return <main className="dashboard-page leads-page"><section className="page-title"><div><h2>Leads</h2><p>Review, qualify, and keep each conversation moving.</p></div><button className="button secondary" onClick={exportCsv}><Download size={17} /> Export CSV</button></section><section className="panel lead-table-panel"><div className="lead-toolbar"><div className="search"><Search size={18} /><input placeholder="Search name or email…" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} /></div>{result && <span>{result.pagination.total} total</span>}</div>{error ? <div className="page-message">{error}</div> : !result ? <Spinner label="Loading leads" /> : result.leads.length === 0 ? <div className="empty"><UsersIcon /><h3>No leads found</h3><p>{search ? 'Try a different name or email.' : 'Incoming project enquiries will appear here.'}</p></div> : <><div className="table-scroll"><table><thead><tr><th>Lead</th><th>Budget</th><th>Message</th><th>Received</th><th>Status</th><th aria-label="Actions" /></tr></thead><tbody>{result.leads.map((lead) => <tr key={lead._id}><td><div className="lead-person"><div className="initial">{lead.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</div><span><strong>{lead.name}</strong><button onClick={() => copyEmail(lead.email)} title="Copy email">{lead.email}<Copy size={13} /></button></span></div></td><td>{lead.budget}</td><td className="message-cell" title={lead.message}>{lead.message}</td><td>{new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(lead.createdAt))}</td><td><select className="status-select" value={lead.status} onChange={(e) => changeStatus(lead, e.target.value)}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></td><td><button className="icon-button danger" onClick={() => deleteLead(lead)} title="Delete lead"><Trash2 size={17} /></button></td></tr>)}</tbody></table></div><Pagination pagination={result.pagination} onPage={setPage} /></>}</section></main>;
}
function Pagination({ pagination, onPage }) { if (pagination.pages < 2) return null; return <div className="pagination"><button disabled={pagination.page === 1} onClick={() => onPage(pagination.page - 1)}>Previous</button><span>Page {pagination.page} of {pagination.pages}</span><button disabled={pagination.page === pagination.pages} onClick={() => onPage(pagination.page + 1)}>Next</button></div>; }
function UsersIcon() { return <span className="empty-icon">◌</span>; }
